const ethers = require('ethers');
const fs = require('fs');
require("dotenv").config({ path: ".env" });
(async () => {


 const provider =new ethers.providers.JsonRpcProvider(process.env.MUMBAI_URL);

  // Use your wallet's private key to deploy the contract
  const privateKey = process.env.PRIVATE_KEY;
  const wallet = new ethers.Wallet(privateKey, provider)

  // Read the contract artifact, which was generated by Remix
  const metadata = JSON.parse(fs.readFileSync('artifacts/contracts/token.sol/Token.json').toString())

  // Set gas limit and gas price, using the default Ropsten provider
//   const price = ethers.utils.formatUnits(await provider.getGasPrice(), 'gwei')
//   const options = {gasLimit: 100000, gasPrice: ethers.utils.parseUnits(price, 'gwei')}

  // Deploy the contract
  const factory = new ethers.ContractFactory(metadata.abi, metadata.bytecode,wallet)
  const contract = await factory.deploy("1000")
  await contract.deployed()
  console.log(`Deployment successful! Contract Address: ${contract.address}`)
})()